on:
  pull_request:
    branches:
      - main
      - master
      - development
  push:
    branches:
      - main
      - master
      - development
    paths:
      - .github/workflows/render-module-rmd.yaml
      - fireSense_dataPrepFit.Rmd
      - fireSense_dataPrepFit.R

name: Render module Rmd

jobs:
  render:
    name: Render module Rmd
    runs-on: ubuntu-20.04

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          Ncpus: 2

      - name: Install additional system dependencies
        run: |
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libgdal-dev \
            libgeos-dev \
            libgit2-dev \
            libglpk-dev \
            libmagick++-dev \
            libproj-dev \
            libudunits2-dev \
            libxml2-dev \
            python3-gdal

      - uses: PredictiveEcology/actions/install-Require@v0
        with:
          GitTag: '5c44205bf407f613f53546be652a438ef1248147'

      - uses: PredictiveEcology/actions/install-SpaDES@v0

      - uses: PredictiveEcology/actions/install-Rmd-pkgs@v0

      - name: Render module Rmd
        run: |
          rmarkdown::render("fireSense_dataPrepFit.Rmd", encoding = "UTF-8")
        shell: Rscript {0}

      - name: Commit results
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit fireSense_dataPrepFit.html -m 'Re-build fireSense_dataPrepFit.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{github.ref}} || echo "No changes to commit"
